version: '3.4'

x-logging:
  &default-logging
  options:
    max-size: '10m'
    max-file: '5'
  driver: json-file

services:
  db:
    image: ${DB_IMAGE:-mysql:8.0}
    restart: ${DB_RESTART_POLICY:-unless-stopped}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-blablabla}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-lampdb}
      MYSQL_USER: ${MYSQL_USER:-db_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-blablabla}
    volumes:
      - ${BASE_PATH:-/data}/mysql:/var/lib/mysql
    networks:
      - default

  web:
    image: ${WEB_IMAGE:-php:7.3.3-apache}
    restart: unless-stopped
    logging: *default-logging
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-lampdb}
      MYSQL_USER: ${MYSQL_USER:-db_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-blablabla}
    labels:
      - "traefik.backend=naturalis"
      - "traefik.enable=true"
      - "traefik.port=${TRAEFIK_WEB_PORT:-80}"
      - "${SITE_URL:-traefik.frontend.rule=Host:lamp.site.nl}"
    volumes:
      - ${BASE_PATH:-/data}/www:/var/www/html
    networks:
      - default

  traefik:
    image: traefik:1.7.10
    container_name: traefik
    restart: unless-stopped
    logging: *default-logging
    ports:
      - 80:80
      - 443:443
      - 8081:8080
    networks:
      - default
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${BASE_PATH:-/data}/traefiklogs/traefik.log:/var/log/traefik.log
      - ${TRAEFIK_TOML_FILE:-./traefik.toml}:/traefik.toml
      - ${CERTDIR:-/etc/letsencrypt}:/etc/letsencrypt

networks:
    default:
    web:
        external: true
