version: '3'

services:

  db:
    image: mattermost/mattermost-prod-db:5.8.0
    read_only: true
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: '10m'
        max-file: '5'
    volumes:
      - ${BASE_PATH:-/data}/postgresql:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env

  app:
    image: mattermost/mattermost-prod-app:5.6.5
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: '10m'
        max-file: '5'
    volumes:
      - ${BASE_PATH:-/data}/config:/mattermost/config:rw
      - ${BASE_PATH:-/data}/data:/mattermost/data:rw
      - ${BASE_PATH:-/data}/logs:/mattermost/logs:rw
      - ${BASE_PATH:-/data}/plugins:/mattermost/plugins:rw
      - ${BASE_PATH:-/data}/client-plugins:/mattermost/client/plugins:rw
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env

  web:
    image: mattermost/mattermost-prod-web:5.8.0
    read_only: true
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: '10m'
        max-file: '5'
    labels:
      - "traefik.backend=naturalis-mattermost"
      - "traefik.enable=true"
      - "traefik.port=80"
      - "${SITE_URL:-traefik.frontend.rule=Host:chat.museum.naturalis.nl}"
    volumes:
      # This directory must have cert files if you want to enable SSL
      - ${BASE_PATH:-/data}/web/cert:/cert:ro
      - /etc/localtime:/etc/localtime:ro
    # Uncomment for SSL
    # environment:
    #  - MATTERMOST_ENABLE_SSL=true
    env_file:
      - .env

  traefik:
    image: traefik:1.7.4
    container_name: traefik
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 8081:8080
    networks:
      - default
      - web
    logging:
      driver: "json-file"
      options:
        max-size: '10m'
        max-file: '5'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${BASE_PATH:-/data}/traefiklogs/traefik.log:/var/log/traefik.log
      - ${TRAEFIK_TOML_FILE:-./traefik.toml}:/traefik.toml
      - ${CERTDIR:-/etc/letsencrypt}:/etc/letsencrypt

networks:
    default:
    web:
        external: true
