version: '3.4'

x-logging:
  &default-logging
  options:
    max-size: '10m'
    max-file: '5'
  driver: json-file

services:
  db1:
    image: ${DB_IMAGE_1:-mysql:8.0}
    restart: ${DB_RESTART_POLICY_1:-unless-stopped}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-blablabla}
      MYSQL_DATABASE: ${MYSQL_DATABASE_1:-lampdb}
      MYSQL_USER: ${MYSQL_USER_1:-db_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD_1:-blablabla}
    volumes:
      - ${BASE_PATH_1:-/data}/mysql:/var/lib/mysql
    networks:
      - default

  web1:
    image: ${WEB_IMAGE_1:-php:7.3.3-apache}
    restart: ${WEB_RESTART_POLICY_1:-unless-stopped}
    logging: *default-logging
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE_1:-lampdb}
      MYSQL_USER: ${MYSQL_USER_1:-db_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD_1:-blablabla}
    labels:
      - traefik.http.routers.web1.entrypoints=https
      - traefik.http.routers.web1.tls.certresolver=${TRAEFIK_CERT_RESOLVER_1:-default}
      - traefik.http.routers.web1.tls=true
      - traefik.http.routers.web1.rule=${SITE_URL_1:-Host(`lamp.site1.nl`)}
    volumes:
      - ${BASE_PATH_1:-/data}/www:${WEB_DOCROOT_1:-/var/www/html}
    networks:
      - default

  db2:
    image: ${DB_IMAGE_2:-busybox:1.30.1}
    restart: ${DB_RESTART_POLICY_2:-no}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-blablabla}
      MYSQL_DATABASE: ${MYSQL_DATABASE_2:-lampdb}
      MYSQL_USER: ${MYSQL_USER_2:-db_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD_2:-blablabla}
    volumes:
      - ${BASE_PATH_2:-/data}/mysql:/var/lib/mysql
    networks:
      - default

  web2:
    image: ${WEB_IMAGE_2:-busybox:1.30.1}
    restart: ${WEB_RESTART_POLICY_2:-no}
    logging: *default-logging
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE_2:-lampdb}
      MYSQL_USER: ${MYSQL_USER_2:-db_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD_2:-blablabla}
    labels:
      - traefik.http.routers.web2.entrypoints=https
      - traefik.http.routers.web2.tls.certresolver=${TRAEFIK_CERT_RESOLVER_2:-default}
      - traefik.http.routers.web2.tls=true
      - traefik.http.routers.web2.rule=${SITE_URL_2:-Host(`lamp.site2.nl`)}
    volumes:
      - ${BASE_PATH_2:-/data}/www:${WEB_DOCROOT_2:-/var/www/html}
    networks:
      - default


  db3:
    image: ${DB_IMAGE_3:-busybox:1.30.1}
    restart: ${DB_RESTART_POLICY_3:-no}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-blablabla}
      MYSQL_DATABASE: ${MYSQL_DATABASE_3:-lampdb}
      MYSQL_USER: ${MYSQL_USER_3:-db_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD_3:-blablabla}
    volumes:
      - ${BASE_PATH_3:-/data}/mysql:/var/lib/mysql
    networks:
      - default

  web3:
    image: ${WEB_IMAGE_3:-busybox:1.30.1}
    restart: ${WEB_RESTART_POLICY_3:-no}
    logging: *default-logging
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE_3:-lampdb}
      MYSQL_USER: ${MYSQL_USER_3:-db_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD_3:-blablabla}
    labels:
      - traefik.http.routers.web3.entrypoints=https
      - traefik.http.routers.web3.tls.certresolver=${TRAEFIK_CERT_RESOLVER_3:-default}
      - traefik.http.routers.web3.tls=true
      - traefik.http.routers.web3.rule=${SITE_URL_3:-Host(`lamp.site3.nl`)}
    volumes:
      - ${BASE_PATH_3:-/data}/www:${WEB_DOCROOT_3:-/var/www/html}
    networks:
      - default


  db4:
    image: ${DB_IMAGE_4:-busybox:1.30.1}
    restart: ${DB_RESTART_POLICY_4:-no}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-blablabla}
      MYSQL_DATABASE: ${MYSQL_DATABASE_4:-lampdb}
      MYSQL_USER: ${MYSQL_USER_4:-db_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD_4:-blablabla}
    volumes:
      - ${BASE_PATH_4:-/data}/mysql:/var/lib/mysql
    networks:
      - default

  web4:
    image: ${WEB_IMAGE_4:-busybox:1.30.1}
    restart: ${WEB_RESTART_POLICY_4:-no}
    logging: *default-logging
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE_4:-lampdb}
      MYSQL_USER: ${MYSQL_USER_4:-db_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD_4:-blablabla}
    labels:
      - traefik.http.routers.web4.entrypoints=https
      - traefik.http.routers.web4.tls.certresolver=${TRAEFIK_CERT_RESOLVER_4:-default}
      - traefik.http.routers.web4.tls=true
      - traefik.http.routers.web4.rule=${SITE_URL_4:-Host(`lamp.site4.nl`)}
    volumes:
      - ${BASE_PATH_4:-/data}/www:${WEB_DOCROOT_4:-/var/www/html}
    networks:
      - default


  db5:
    image: ${DB_IMAGE_5:-busybox:1.30.1}
    restart: ${DB_RESTART_POLICY_5:-no}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-blablabla}
      MYSQL_DATABASE: ${MYSQL_DATABASE_5:-lampdb}
      MYSQL_USER: ${MYSQL_USER_5:-db_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD_5:-blablabla}
    volumes:
      - ${BASE_PATH_5:-/data}/mysql:/var/lib/mysql
    networks:
      - default

  web5:
    image: ${WEB_IMAGE_5:-busybox:1.30.1}
    restart: ${WEB_RESTART_POLICY_5:-no}
    logging: *default-logging
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE_5:-lampdb}
      MYSQL_USER: ${MYSQL_USER_5:-db_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD_5:-blablabla}
    labels:
      - traefik.http.routers.web5.entrypoints=https
      - traefik.http.routers.web5.tls.certresolver=${TRAEFIK_CERT_RESOLVER_5:-default}
      - traefik.http.routers.web5.tls=true
      - traefik.http.routers.web5.rule=${SITE_URL_5:-Host(`lamp.site5.nl`)}
    volumes:
      - ${BASE_PATH_5:-/data}/www:${WEB_DOCROOT_5:-/var/www/html}
    networks:
      - default

  traefik:
    image: traefik:2.1
    container_name: traefik
    restart: unless-stopped
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_HOSTED_ZONE_ID=${AWS_HOSTED_ZONE_ID}
    ports:
      - 80:80
      - 443:443
      - 8081:8080
    networks:
      - default
      - web
    logging: *default-logging
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik:/etc/traefik

networks:
    default:
    web:
        external: true
